# Generated by Django 5.2.10 on 2026-03-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_squadmembership_membershipfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='squadmembership',
            name='role',
        ),
        migrations.RemoveField(
            model_name='squadmembership',
            name='squad',
        ),
        migrations.RemoveField(
            model_name='squadmembership',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль в отряде', 'verbose_name_plural': 'Роли в отрядах'},
        ),
        migrations.DeleteModel(
            name='MembershipFee',
        ),
        migrations.DeleteModel(
            name='SquadMembership',
        ),
    ]
