# Generated by Django 5.2.10 on 2026-04-04 16:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passport_remove_squadmembership_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Паспорт', 'verbose_name_plural': 'Паспорта'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_day',
            field=models.DateField(default='2000-01-01', verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='passport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 4, 16, 28, 32, 492607, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passport',
            name='date_of_issue',
            field=models.DateField(default=datetime.datetime(2026, 4, 4, 16, 28, 36, 590611, tzinfo=datetime.timezone.utc), verbose_name='Дата выдачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passport',
            name='issued_by',
            field=models.CharField(default=datetime.datetime(2026, 4, 4, 16, 28, 38, 669590, tzinfo=datetime.timezone.utc), help_text='Наименование органа, выдавшего паспорт', max_length=255, verbose_name='Кем выдан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passport',
            name='number',
            field=models.CharField(default=111111, help_text='6 цифр, например: 567890', max_length=6, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passport',
            name='registration_address',
            field=models.TextField(default='Кампус двфу', help_text='Полный адрес по месту жительства', verbose_name='Адрес регистрации'),
        ),
        migrations.AddField(
            model_name='passport',
            name='series',
            field=models.CharField(default=1111, help_text='4 цифры, например: 1234', max_length=4, verbose_name='Серия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passport',
            name='unit_code',
            field=models.CharField(default=0, help_text='Формат: XXX-XXX или XXXXXX (6-7 символов)', max_length=7, verbose_name='Код подразделения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='passport',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserStudyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('IMKT', 'ИМКТ'), ('VI', 'ВИ'), ('PISH', 'ПИШ'), ('SHIGN', 'ШИГН'), ('IMO', 'ИМО'), ('PI', 'ПИ'), ('ITPM', 'ИТПМ'), ('SHMINZ', 'ШМИНЖ'), ('IFKS', 'ИФКС'), ('USH', 'ЮШ'), ('SHEM', 'ШЭМ'), ('SHP', 'ШП')], verbose_name='Факультет')),
                ('student_group', models.CharField(max_length=50, verbose_name='Номер группы')),
                ('study_form', models.CharField(choices=[('Full-time', 'Очная'), ('Full-part-time', 'Очно-заочная'), ('Part-time', 'Заочная')], default='Full-time', verbose_name='Форма обучения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Данные по учебе',
                'verbose_name_plural': 'Данные по учебе',
                'unique_together': {('user',)},
            },
        ),
    ]
