# Generated by Django 5.2.10 on 2026-04-12 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(default='commander', unique=True),
        ),
        migrations.AlterField(
            model_name='userstudyinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
