# Generated by Django 5.2.10 on 2026-04-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_slug_alter_userstudyinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
