# Generated by Django 5.2.10 on 2026-04-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_role_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passport',
            options={'verbose_name': 'Паспорт', 'verbose_name_plural': 'Паспорта'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Роль в отряде', 'verbose_name_plural': 'Роли в отрядах'},
        ),
        migrations.AlterUniqueTogether(
            name='userstudyinfo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='passport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Системная роль'),
        ),
        migrations.AddField(
            model_name='role',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.role', verbose_name='Родительская роль'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='Права'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='registration_address',
            field=models.TextField(verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='unit_code',
            field=models.CharField(help_text='Формат 123-456 или 123456', max_length=7, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='userstudyinfo',
            name='faculty',
            field=models.CharField(choices=[('IMKT', 'ИМКТ'), ('VI', 'ВИ'), ('PISH', 'ПИШ'), ('SHIGN', 'ШИГН'), ('IMO', 'ИМО'), ('PI', 'ПИ'), ('ITPM', 'ИТПМ'), ('SHMINZ', 'ШМИНЖ'), ('IFKS', 'ИФКС'), ('USH', 'ЮШ'), ('SHEM', 'ШЭМ'), ('SHP', 'ШП')], max_length=20, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='userstudyinfo',
            name='study_form',
            field=models.CharField(choices=[('Full-time', 'Очная'), ('Full-part-time', 'Очно-заочная'), ('Part-time', 'Заочная')], default='Full-time', max_length=20, verbose_name='Форма обучения'),
        ),
    ]
