# Generated by Django 5.2.10 on 2026-04-27 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_passport_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudyinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
