FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    netcat-traditional \
    && rm -rf /var/lib/apt/lists/*

COPY req.txt /app/
RUN pip install --no-cache-dir -r req.txt

COPY Admissions_squad /app/

EXPOSE 8000

CMD ["gunicorn", "admission.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3", "--timeout", "120"]
