# Generated by Django 5.2.10 on 2026-02-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название отряда')),
                ('description', models.TextField(blank=True, verbose_name='Описание отряда')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
