# Generated by Django 5.2.10 on 2026-03-03 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passport_remove_squadmembership_role_and_more'),
        ('squads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squad',
            options={'verbose_name': 'Отряд', 'verbose_name_plural': 'Отряды'},
        ),
        migrations.CreateModel(
            name='SquadMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='squads.squad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membersips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Членство в отряде',
                'verbose_name_plural': 'Челенства в отрядах',
            },
        ),
        migrations.CreateModel(
            name='MembershipFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='squads.squadmembership')),
            ],
            options={
                'verbose_name': 'Членский взнос',
                'verbose_name_plural': 'Челенские взносы',
            },
        ),
    ]
