# Generated by Django 5.2.10 on 2026-03-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0002_alter_squad_options_squadmembership_membershipfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='LSO_directions',
            field=models.CharField(default='Студенческие сервисные отряды', verbose_name='Направление ЛСО'),
        ),
        migrations.AddField(
            model_name='squad',
            name='employer',
            field=models.CharField(default='ФГАОУ ВО "ДВФУ"', verbose_name='Работодатель'),
        ),
        migrations.AddField(
            model_name='squad',
            name='region',
            field=models.CharField(default='Приморский край', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='squad',
            name='regional_office',
            field=models.CharField(default='Приморское РО', verbose_name='Региональное отделение'),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='birth_day',
            field=models.DateTimeField(default='2026-03-09 18:00', verbose_name='День рожденья'),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='faculty',
            field=models.CharField(choices=[('IMKT', 'ИМКТ'), ('VI', 'ВИ'), ('PISH', 'ПИШ'), ('SHIGN', 'ШИГН'), ('IMO', 'ИМО'), ('PI', 'ПИ'), ('ITPM', 'ИТПМ'), ('SHMINZ', 'ШМИНЖ'), ('IFKS', 'ИФКС'), ('USH', 'ЮШ'), ('SHEM', 'ШЭМ'), ('SHP', 'ШП')], default='IMKT', verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='student_group',
            field=models.CharField(default='Б9122-09.03.04', verbose_name='Номер группы'),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='study_form',
            field=models.CharField(choices=[('Full-time', 'Очная'), ('Full-part-time', 'Очно-заочная'), ('Part-time', 'Заочная')], default='Full-time', verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='ticket_number',
            field=models.CharField(blank=True, null=True, verbose_name='Номер членского билета'),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='university',
            field=models.CharField(default='ФГАОУ ВО "ДВФУ"', verbose_name='Место учёбы'),
        ),
    ]
