# Generated by Django 5.2.10 on 2026-03-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0003_squad_lso_directions_squad_employer_squad_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость взноса'),
        ),
        migrations.AlterField(
            model_name='membershipfee',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='membershipfee',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Уплачен'),
        ),
    ]
