# Generated by Django 5.2.10 on 2026-03-09 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0004_alter_membershipfee_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadmembership',
            name='birth_day',
            field=models.DateField(default=datetime.date(2026, 3, 9), verbose_name='День рожденья'),
        ),
    ]
