# Generated by Django 5.2.10 on 2026-03-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0005_alter_squadmembership_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipfee',
            name='expires_at',
            field=models.DateField(verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='membershipfee',
            name='paid_at',
            field=models.DateField(auto_now_add=True, verbose_name='Уплачен'),
        ),
    ]
