# Generated by Django 5.2.10 on 2026-03-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0006_alter_membershipfee_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipfee',
            name='expires_at',
            field=models.DateField(verbose_name='Дата истечения'),
        ),
        migrations.AlterField(
            model_name='membershipfee',
            name='paid_at',
            field=models.DateField(verbose_name='Дата уплаты'),
        ),
    ]
