# Generated by Django 5.2.10 on 2026-04-04 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0007_alter_membershipfee_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipfee',
            options={'verbose_name': 'Членский взнос', 'verbose_name_plural': 'Членские взносы'},
        ),
        migrations.AlterModelOptions(
            name='squadmembership',
            options={'verbose_name': 'Членство в отряде', 'verbose_name_plural': 'Членства в отрядах'},
        ),
        migrations.RenameField(
            model_name='squad',
            old_name='LSO_directions',
            new_name='lso_directions',
        ),
        migrations.AlterUniqueTogether(
            name='squadmembership',
            unique_together={('user', 'squad')},
        ),
        migrations.AlterField(
            model_name='squadmembership',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membersips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='squadmembership',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='squadmembership',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='squadmembership',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='squadmembership',
            name='student_group',
        ),
        migrations.RemoveField(
            model_name='squadmembership',
            name='study_form',
        ),
    ]
