# Generated by Django 5.2.10 on 2026-04-12 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_slug_alter_userstudyinfo_user'),
        ('squads', '0009_alter_squadmembership_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='squadmembership',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='squadmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_membership_per_user'),
        ),
    ]
