# Generated by Django 5.2.10 on 2026-06-02 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('system', 'Системное уведомление'), ('user_registered', 'Новый пользователь'), ('availability_form_opened', 'Открыта форма доступности'), ('schedule_published', 'График опубликован'), ('schedule_changed', 'График изменён'), ('change_request_created', 'Новая заявка'), ('change_request_approved', 'Заявка одобрена'), ('change_request_rejected', 'Заявка отклонена')], default='system', max_length=64, verbose_name='Тип события')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, verbose_name='Текст уведомления')),
                ('object_url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка в интерфейсе')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('email_required', models.BooleanField(default=False, verbose_name='Требуется email')),
                ('email_to', models.EmailField(blank=True, max_length=254, verbose_name='Email получателя')),
                ('email_subject', models.CharField(blank=True, max_length=255, verbose_name='Тема письма')),
                ('email_body', models.TextField(blank=True, verbose_name='Текст письма')),
                ('email_status', models.CharField(choices=[('not_required', 'Email не требуется'), ('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки')], default='not_required', max_length=32, verbose_name='Статус email')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки email')),
                ('email_error', models.TextField(blank=True, verbose_name='Ошибка email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['event_type'], name='notificatio_event_t_c22bab_idx'), models.Index(fields=['email_status'], name='notificatio_email_s_9090dd_idx')],
            },
        ),
    ]
