# Generated by Django 5.2.10 on 2026-04-12 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('squads', '0010_alter_squadmembership_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('open', 'Открыта'), ('closed', 'Закрыта')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_forms', to='squads.squad')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityFormDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='rosters.availabilityform')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('form', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AvailabilityFormShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_kind', models.CharField(choices=[('primary', 'Основная смена'), ('extra', 'Дополнительная смена')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('starts_at', models.TimeField(blank=True, null=True)),
                ('ends_at', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='rosters.availabilityformday')),
            ],
            options={
                'ordering': ['starts_at', 'id'],
                'unique_together': {('day', 'shift_kind')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'Архив')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='squads.squad')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='squads.squadmembership')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rosters.schedule')),
            ],
            options={
                'ordering': ['date', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('cancel', 'Не могу выйти'), ('swap', 'Прошу замену'), ('time_change', 'Изменение времени')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_schedule_change_requests', to=settings.AUTH_USER_MODEL)),
                ('target_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_change_requests', to='squads.squadmembership')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='rosters.scheduleentry')),
            ],
        ),
        migrations.CreateModel(
            name='QrToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='rosters.scheduleentry')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('required_people', models.PositiveIntegerField(default=1)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='rosters.schedule')),
            ],
            options={
                'ordering': ['date', 'starts_at'],
            },
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rosters.scheduleneed'),
        ),
        migrations.CreateModel(
            name='ScheduleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_made', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_made', to=settings.AUTH_USER_MODEL)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='rosters.scheduleentry')),
            ],
        ),
        migrations.CreateModel(
            name='WorkBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_blocks', to='squads.squad')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('squad', 'code')},
            },
        ),
        migrations.AddField(
            model_name='scheduleneed',
            name='work_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_needs', to='rosters.workblock'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='work_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rosters.workblock'),
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='squads.squadmembership')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rosters.availabilityformshift')),
            ],
            options={
                'unique_together': {('shift', 'membership')},
            },
        ),
    ]
