# Generated by Django 5.2.10 on 2026-04-27 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='availability_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='rosters.availabilityform', verbose_name='Форма доступности'),
        ),
    ]
