# Generated by Django 5.2.10 on 2026-05-24 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0002_schedule_availability_form'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('check_in', 'Приход'), ('check_out', 'Уход')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='qrtoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='action',
            field=models.CharField(choices=[('check_in', 'Приход'), ('check_out', 'Уход')], default='check_in', max_length=20),
        ),
        migrations.AddIndex(
            model_name='qrtoken',
            index=models.Index(fields=['token'], name='rosters_qrt_token_b97e02_idx'),
        ),
        migrations.AddIndex(
            model_name='qrtoken',
            index=models.Index(fields=['entry', 'action', 'is_used'], name='rosters_qrt_entry_i_a3014f_idx'),
        ),
        migrations.AddField(
            model_name='attendanceactionlog',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='rosters.scheduleentry'),
        ),
        migrations.AddField(
            model_name='attendanceactionlog',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendanceactionlog',
            index=models.Index(fields=['created_at'], name='rosters_att_created_abd231_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceactionlog',
            index=models.Index(fields=['entry', 'action'], name='rosters_att_entry_i_d7d970_idx'),
        ),
    ]
