# Generated by Django 5.2.10 on 2026-05-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0003_attendanceactionlog_alter_qrtoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирована'), ('in_progress', 'На смене'), ('attended', 'Посетил'), ('absent', 'Не посетил'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='planned', max_length=20),
        ),
    ]
