# Generated by Django 5.2.10 on 2026-05-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0004_alter_scheduleentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityform',
            name='allow_work_block_choice',
            field=models.BooleanField(default=False, verbose_name='Разрешить выбор блока работы'),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='preferred_work_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_slots', to='rosters.workblock', verbose_name='Предпочитаемый блок работы'),
        ),
    ]
