# Generated by Django 5.2.10 on 2026-06-01 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0005_availabilityform_allow_work_block_choice_and_more'),
        ('squads', '0010_alter_squadmembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulechangerequest',
            name='target_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_requests', to='squads.squadmembership', verbose_name='Участник на замену'),
        ),
    ]
